[build-system]
requires = ["scikit-build-core", "nanobind", "pylmcf @ git+https://github.com/michalsta/pylmcf"]
build-backend = "scikit_build_core.build"

[project]
name = "wnetalign"
version = "0.0.1"
