[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "wnetalign"
version = "0.0.1"
description = "Python implementation of spectral alignment using Wasserstein metric"
authors = [
    { name="Michał Startek", email="michal.startek@mimuw.edu.pl" }
]
dependencies = ["pylmcf", "wnet", "numpy"]
